# Generated by Django 4.2.16 on 2024-12-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_post_created_at_post_is_published_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Заголовок'),
        ),
    ]
